#!/bin/sh
# -*- mode: sh; indent-tabs-mode: t -*-
#
# 2019 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.

case $("${__explorer}/os")
in
	netbsd)
		postgres_user='pgsql'
		;;
	openbsd)
		postgres_user='_postgresql'
		;;
	*)
		postgres_user='postgres'
		;;
esac

pg_conf_path=$(su - "${postgres_user}" -c "psql postgres -twAc \
	'SHOW config_file'" 2>/dev/null || true)

pg_auto_conf_path=$(echo "${pg_conf_path}" | sed -e 's/.conf$/.auto.conf/')

if [ -f "${pg_auto_conf_path}" ]
then
	echo "${pg_auto_conf_path}"
elif [ -f "${pg_conf_path}" ]
then
	echo "${pg_conf_path}"
fi
