#!/bin/sh -e
#
# 2011 Ramon Salvadó (rsalvado at gnuine dot com)
# 2012-2015 Steven Armstrong (steven-cdist at armstrong.cc)
# 2012-2019 Nico Schottelius (nico-cdist at schottelius.org)
# 2020 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# This type allows to configure the desired localtime timezone.

TZ=$(cat "${__object:?}/parameter/tz")
os=$(cat "${__global:?}/explorer/os")
localtime_file=/etc/localtime
zoneinfo_file=$(cat "${__object:?}/explorer/zoneinfo_file")

invalid_timezone() {
	# NOTE: When the tzdata package was just installed, this might produce an
	# invalid timezone error because the explorer has been run before the
	# installation.
	printf 'Invalid timezone: %s\n' "${TZ}" >&2
	exit 1
}

# Some OSes require a timezone package to be installed first:
case ${os}
in
	(archlinux|alpine|debian|devuan|ubuntu|centos|redhat|scientific)
		__package tzdata --state present
		export require=__package/tzdata
		;;
	(suse)
		__package timezone --state present
		export require=__package/timezone
		;;
esac

# Configure the timezone
case ${os}
in
	(alpine|coreos|debian|devuan|ubuntu)
		test -n "${zoneinfo_file}" || invalid_timezone

		echo "${TZ}" | __file /etc/timezone --source -
		;;
	(centos|redhat|scientific)
		test -n "${zoneinfo_file}" || invalid_timezone

		__file /etc/sysconfig/clock \
			--owner root --group root --mode 644 \
			--state exists
		require=__file/etc/sysconfig/clock \
		__key_value /etc/sysconfig/clock:ZONE \
			--file /etc/sysconfig/clock \
			--key ZONE \
			--delimiter '=' --exact_delimiter \
			--value "\"${TZ}\""
		;;
	(*)
		echo "Your operating system (${os}) is currently not supported by this type (${__type##*/})." >&2
		echo "Please contribute an implementation for it if you can." >&2
		exit 1
		;;
esac

__link "${localtime_file}" --type symbolic --source "${zoneinfo_file}"
