#!/bin/sh -e
#
# 2020 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

os=$(cat "${__global}/explorer/os")

if test -f "${__object}/parameter/type"
then
	type=$(cat "${__object}/parameter/type")
else
	# Guess the type based on the operating system
	case $os
	in
		debian)
			os_major=$(grep -o '^[0-9][0-9]*' "${__global}/explorer/os_version")
			if test "${os_major}" -ge 7
			then
				type=ifupdown.d
			else
				echo 'Debian versions older than 7 (wheezy) are not (currently) supported' >&2
				exit 1
			fi
			;;
		devuan)
			type=ifupdown.d
			;;
		*)
			echo "Don't know how to manage interfaces on: ${os}" >&2
			exit 1
			;;
	esac
fi

state=$(cat "${__object}/parameter/state")

set -- "$@" "${__object_id}" --state "${state}"

cd "${__object}/parameter"
for param in *
do
	if [ "${param}" != 'type' ] && [ "${param}" != 'state' ]
	then
		set -- "$@" --"${param}"
		if ! grep -q "^${param}$" "${__type}/parameter/boolean"
		then
			set -- "$@" "$(cat "${param}")"
		fi
	fi
done


__interface_$type "$@"
