#!/bin/sh -e
#
# 2014 Steven Armstrong (steven-cdist at armstrong.cc)
# 2023 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

os=$(cat "${__global:?}/explorer/os")
state_should=$(cat "${__object:?}/parameter/state")

case ${os}
in
	(centos|fedora|redhat|scientific)
		repo_name=${__object_id:?}

		repo_file="/etc/yum.repos.d/${repo_name}.repo"

		__file "${repo_file}" \
			--owner 0 --group 0 --mode 0644 \
			--state "${state_should}" \
			--source - <<-EOF
		$("${__type:?}/files/repo.template")
		EOF
		;;
	*)
		echo "Your operating system ($os) is currently not supported by this type (${__type##*/})." >&2
		echo "Please contribute an implementation for it if you can." >&2
		exit 1
		;;
esac
