#!/bin/sh -e
# -*- mode: sh; indent-tabs-mode: t -*-
#
# 2020 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

set -- --state "${__object}/parameter/state"

if test -f "${__object}/parameter/onboot"
then
	set -- "$@" --auto
fi
if test -f "${__object}/parameter/hotplug"
then
	set -- "$@" --hotplug
fi

# Generate appropriate parameters for backend type
bootproto=$(cat "${__object}/parameter/bootproto")
case $bootproto
in
	(dhcp)
		# TODO
		;;
	(static)
		# TODO
		;;
	(manual)
		# TODO
		;;
	(*)
		exit 1
		;;
esac

# Instantiate backend type
__interface_ifupdown.d "@"
