#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
# 2019 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Get an existing groups group entry.
#

not_supported() {
	echo "Your operating system ($("$__explorer/os")) is currently not supported." >&2
	echo "Cannot extract group information." >&2
	echo "Please contribute an implementation for it if you can." >&2
	exit 1
}


if [ -f "$__object/parameter/gid" ]
then
	gid=$(cat "$__object/parameter/gid")
	if command -v getent >/dev/null
	then
		getent group "$gid" || true
	elif command -v dscl >/dev/null
	then
		# Mac OS X uses Directory Service to manage users and groups
		dscl_grep() {
			awk -F':( +|$)' "\$1 == \"$1\" { if (\$2) print \$2; while (getline > 0) { if (substr(\$0, 0, 1) == \" \") print substr(\$0, 2); else break } }"
		}

		if gprops=$(dscl -q . -read "/Groups/${name}")
		then
			printf '%s:%s:%u:%s\n' \
				"$name" \
				"$(echo "$gprops" | dscl_grep Password)" \
				"$(echo "$gprops" | dscl_grep PrimaryGroupID)" \
				"$(echo "$gprops" | dscl_grep GroupMembership | tr ' ' ',')"
		fi
	elif [ -f /etc/group ]; then
		grep -E "^(${gid}|([^:]+:){2}${gid}):" /etc/group || true
	else
		not_supported
	fi
fi
