#!/bin/sh -e
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
# 2019-2020 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Get an existing users shadow entry.
#

name=$__object_id

case $("${__explorer}/os")
in
  freebsd)
    database='passwd'
    db_file='/etc/master.passwd'
    ;;
  macosx)
    # Mac OS X doesn’t use files to store user accounts anymore.
    # Most system users can still be found there, though.
    # XXX: It is unclear if these files are updated by the system utilities!
    db_file='/etc/master.passwd'
    ;;
  netbsd|openbsd)
    db_file='/etc/master.passwd'
    ;;
  *)
    # Default to using shadow passwords
    database='shadow'
    ;;
esac
test -n "${db_file}" || db_file="/etc/${database}"

if test -n "${database}" && command -v getent >/dev/null 2>&1
then
  # shellcheck disable=SC2015
  getent "${database}" "${name}" 2>/dev/null && exit || true  # fallback to file
fi
if test -f "${db_file}"
then
  grep -e "^${name}:" "${db_file}" || true  # ignore failure
fi
