#!/bin/sh -e

shquot() {
sed -e "s/'/'\\\\''/g" -e "1s/^/'/" -e "\$s/\$/'/" <<-EOF
$*
EOF
}

if grep -xq 'missing\|match' "${__object:?}/explorer/state"
then
    exit 0
fi

os=$(cat "${__global:?}/explorer/os")

src="/${__object_id:?}"

dst=$(sed 's|/$||' "${__object:?}/parameter/destination")

cmd=''

case ${src}
in
    # https://git.savannah.gnu.org/cgit/tar.git/tree/src/suffix.c?h=release_1_34#n29
    (*.tar|*.tgz|*.tar.*|*.txz|*.tbz2)
        cmd="mkdir -p $(shquot "${dst}") && tar --directory=$(shquot "${dst}") --extract --file=$(shquot "${src}")"

        if [ -f "${__object:?}/parameter/tar-strip" ]
        then
            tar_strip=$(cat "${__object:?}/parameter/tar-strip")

            cmd="${cmd} --strip-components=${tar_strip}"
        fi

        if [ -f "${__object:?}/parameter/tar-extra-args" ]
        then
            tar_extra_args=$(cat "${__object:?}/parameter/tar-extra-args")

            cmd="${cmd} ${tar_extra_args}"
        fi
    ;;
    (*.7z)
        case ${os}
        in
            centos|almalinux|eurolinux|rocky|fedora|redhat)
                cmd='7za'
            ;;
            *)
                cmd='7zr'
            ;;
        esac

        cmd="${cmd} e -aoa -o$(shquot "${dst}") $(shquot "${src}")"
    ;;
    (*.bz2)
        cmd="bunzip2 --stdout $(shquot "${src}") >$(shquot "${dst}")"
    ;;
    (*.gz)
        cmd="gunzip --stdout $(shquot "${src}") >$(shquot "${dst}")"
    ;;
    (*.lzma|*.xz)
        cmd="xz --uncompress --stdout $(shquot "${src}") >$(shquot "${dst}")"
    ;;
    (*.rar)
        cmd="unrar x -o+ $(shquot "${src}") $(shquot "${dst}/")"
    ;;
    (*.zip)
        cmd="unzip -o $(shquot "${src}") -d $(shquot "${dst}")"
    ;;
esac

if [ -f "${__object:?}/parameter/backup-destination" ]
then
    backup_dst="${dst:?}.skonfig__unpack_backup_$(date +%s)"
    printf 'if [ -e %s ]; then mv %s %s; fi\n' \
        "$(shquot "${dst}")" "$(shquot "${dst}")" "$(shquot "${backup_dst}")"
    printf 'backed up %s to %s\n' "${dst}" "${backup_dst}" >>"${__messages_out:?}"
fi

printf '%s\n' "${cmd}"
printf 'unpacked to %s\n' "${dst}" >>"${__messages_out:?}"

if [ -f "${__object:?}/parameter/sum-file" ]
then
    sum_file=$(cat "${__object:?}/parameter/sum-file")
else
    sum_file="${src}.skonfig__unpack_sum"
fi

printf "cksum %s | awk '{ print \$1\$2 }' >%s\\n" \
    "$(shquot "${src}")" "$(shquot "${sum_file}")"

if [ ! -f "${__object:?}/parameter/preserve-archive" ]
then
    printf 'rm -f %s\n' "$(shquot "${src}")"
    printf 'removed archive %s\n' "${src}" >>"${__messages_out:?}"
fi

if [ -f "${__object:?}/parameter/onchange" ]
then
    cat "${__object:?}/parameter/onchange"
fi
