#!/bin/sh -e

os=$(cat "${__global:?}/explorer/os")

src="/${__object_id:?}"

case ${src}
in
    (*.tar|*.tar.*|*.t??|*.t???)
        # require tar to unpack tar
        case ${os}
        in
            (gentoo)
                __package app-arch/tar
            ;;
            (netbsd)
                # part of the base system
            ;;
            (openwrt)
                # OpenWrt ships BusyBox tar in the base system
            ;;
            (*)
                __package tar
            ;;
        esac
    ;;
esac

case ${src}
in
    (*.7z)
        case ${os}
        in
            (alpine)
                __package 7zip
            ;;
            (gentoo)
                __package app-arch/p7zip
            ;;
            (openwrt)
                echo 'the 7z format is not supported on OpenWrt' >&2
                exit 1
            ;;
            (*)
                __package p7zip
            ;;
        esac
    ;;
    (*.cpio)
        case ${os}
        in
            (gentoo)
                __package app-arch/cpio
            ;;
            (freebsd|netbsd|openbsd)
                # part of the base system
            ;;
            (openwrt)
                echo 'the cpio format is not supported on OpenWrt' >&2
                exit 1
            ;;
            (*)
                __package cpio
            ;;
        esac
    ;;
    (*.gz|*.tgz)
        case ${os}
        in
            (alpine|openwrt)
                # use BusyBox gzip(1)
            ;;
            (freebsd|netbsd|openbsd)
                # part of the base system
            ;;
            (gentoo)
                __package app-arch/gzip
            ;;
            (*)
                __package gzip
            ;;
        esac
    ;;
    (*.bz2|*.tbz2)
        case ${os}
        in
            (freebsd|netbsd)
                # part of the base system
            ;;
            (gentoo)
                __package app-arch/bzip2
            ;;
            (*)
                __package bzip2
            ;;
        esac
    ;;
    (*.lzma|*.xz|*.txz)
        case ${os}
        in
            (alpine|centos|almalinux|eurolinux|rocky|openbsd|openwrt)
                __package xz
            ;;
            (debian|ubuntu|devuan)
                __package xz-utils
            ;;
            (freebsd|netbsd)
                # part of the base system
            ;;
            (gentoo)
                __package app-arch/xz-utils
            ;;
        esac
    ;;
    (*.pax)
        case ${os}
        in
            (gentoo)
                __package app-arch/pax
            ;;
            (*)
                __package pax
            ;;
        esac
    ;;
    (*.rar)
        case ${os}
        in
            (gentoo)
                __package app-arch/unrar
            ;;
            (*)
                __package unrar
            ;;
        esac
    ;;
    (*.xar)
        case ${os}
        in
            (gentoo)
                __package app-arch/xar
            ;;
            (*)
                __package xar
            ;;
        esac
    ;;
    (*.zip)
        case ${os}
        in
            (freebsd|netbsd)
                # part of the base system
            ;;
            (gentoo)
                __package app-arch/unzip
            ;;
            (*)
                __package unzip
            ;;
        esac
    ;;
    (*.Z)
        case ${os}
        in
            (alpine)
                # BusyBox gzip(1) supports decompression of POSIX compress files
            ;;
            (debian|devuan|ubuntu)
                # /bin/uncompress is provided by gzip
                __package gzip
            ;;
            (freebsd|netbsd|openbsd)
                # part of the base system
            ;;
            (gentoo)
                __package app-arch/ncompress
            ;;
            (openwrt)
                printf 'the POSIX compress format is not supported on %s' "${os}" >&2
                exit 1
            ;;
        esac
    ;;
    (*.zst)
        case ${os}
        in
            (freebsd)
                # part of the base system
            ;;
            (*)
                __package zstd
            ;;
        esac
    ;;
esac
