#!/bin/sh -e

os=$(cat "${__global:?}/explorer/os")

src="/${__object_id:?}"

case ${src}
in
    (*.tar|*.tar.*|*.t??|*.t???)
        # require tar to unpack tar
        case ${os}
        in
            (gentoo)
                __package app-arch/tar
            ;;
            (openwrt)
                # OpenWrt ships BusyBox tar in the base system
            ;;
            (*)
                __package tar
            ;;
        esac
    ;;
esac

case ${src}
in
    (*.7z)
        case ${os}
        in
            (alpine)
                __package 7zip
            ;;
            (gentoo)
                __package app-arch/p7zip
            ;;
            (openwrt)
                echo 'the 7z format is not supported on OpenWrt' >&2
                exit 1
            ;;
            (*)
                __package p7zip
            ;;
        esac
    ;;
    (*.gz|*.tgz)
        case ${os}
        in
            (gentoo)
                __package app-arch/gzip
            ;;
            (*)
                __package gzip
            ;;
        esac
    ;;
    (*.bz2|*.tbz2)
        case ${os}
        in
            (freebsd)
                # bzip2 is part of FreeBSD base system
            ;;
            (gentoo)
                __package app-arch/bzip2
            ;;
            (*)
                __package bzip2
            ;;
        esac
    ;;
    (*.lzma|*.xz|*.txz)
        case ${os}
        in
            (debian|ubuntu|devuan)
                __package xz-utils
            ;;
            (gentoo)
                __package app-arch/xz-utils
            ;;
            (alpine|centos|almalinux|eurolinux|rocky|openwrt)
                __package xz
            ;;
        esac
    ;;
    (*.rar)
        case ${os}
        in
            (gentoo)
                __package app-arch/unrar
            ;;
            (*)
                __package unrar
            ;;
        esac
    ;;
    (*.zip)
        case ${os}
        in
            (gentoo)
                __package app-arch/unzip
            ;;
            (*)
                __package unzip
            ;;
        esac
    ;;
esac
