#!/bin/sh -e
#
# 2014 Daniel Heule  (hda at sfs.biz)
# 2014 Thomas Oettli (otho at sfs.biz)
# 2021 Dennis Camera (cdist at dtnr.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# Prints the number of CPUs that are installed (aka. sockets)
#

case $("${__explorer:?}/os")
in
	(macosx)
		system_profiler SPHardwareDataType \
		| awk -F': ' '/ *Number of Processors:/ { print $2 }'
		;;
	(*)
		# NOTE: Prefer /proc/cpuinfo if possible because some container engines
		#       only fake /proc/cpuinfo.
		if test -r /proc/cpuinfo
		then
			sockets=$(grep '^physical id	:' /proc/cpuinfo | sort -u | wc -l)
			if test $((sockets)) -gt 0
			then
				echo $((sockets))
				exit 0
			fi
		fi

		if command -v lscpu >/dev/null 2>&1
		then
			lscpu_parse=$(lscpu -p) &&
			sockets=$(awk -F, '/^[^#]/ { x[$3]++ } END { for (k in x) i++; print i }' <<-EOF
				${lscpu_parse}
				EOF
				)

			if test $((sockets)) -gt 0
			then
				echo $((sockets))
				exit
			fi
		fi

		echo 1  # fallback
		;;
esac
