#!/bin/sh -e
#
# 2019 Ander Punnar (ander-at-kvlt-dot-ee)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# Returns a sorted list of all network interfaces known to the system (one per line)


case $(uname -s)
in
	FreeBSD|OpenBSD)
		ifconfig -a | sed -e '/^[a-z0-9]*:/!d' -e 's/:.*$//'
		;;
	NetBSD)
		PATH="${PATH}:/usr/local/sbin:/usr/sbin:/sbin"
		sysctl -e net.interfaces. | cut -d= -f1 | cut -d. -f3
		;;
	SunOS)
		# Note: Solaris' ifconfig duplicates interfaces (once for IPv4, once for IPv6)
		ifconfig -a | sed -e '/^[a-z0-9]*:/!d' -e 's/:.*$//'
		# Alternative: Use dladm, which ignores lo, though.
		# dladm show-link -po link
		;;
	*)
		if command -v ip >/dev/null 2>&1
		then
			ip -o link show | sed -n 's/^[0-9]\+: \(.\+\): <.*/\1/p'
		elif command -v ifconfig >/dev/null 2>&1
		then
			ifconfig -a | sed -n -r 's/^(.*)(:[[:space:]]*flags=|Link encap).*/\1/p'
		fi
		;;
esac \
 | sort -u
