#!/bin/sh -e
#
# 2014 Daniel Heule  (hda at sfs.biz)
# 2014 Thomas Oettli (otho at sfs.biz)
# Copyright 2017, Philippe Gregoire <pg@pgregoire.xyz>
# 2020 Dennis Camera <dennis.camera at ssrq-sds-fds.ch>
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# Returns the amount of memory available to the system in kibibytes (kiB).

str2bytes() {
	awk -F' ' \
	'!$2 || $2 == "B" { print $1 }
	 $2 ==  "kB" { print $1 * 1000 }
	 $2 ==  "MB" { print $1 * 1000 * 1000 }
	 $2 ==  "GB" { print $1 * 1000 * 1000 * 1000 }
	 $2 ==  "TB" { print $1 * 1000 * 1000 * 1000 * 1000 }
	 $2 == "kiB" { print $1 * 1024 }
	 $2 == "MiB" { print $1 * 1024 * 1024 }
	 $2 == "GiB" { print $1 * 1024 * 1024 * 1024 }
	 $2 == "TiB" { print $1 * 1024 * 1024 * 1024 * 1024 }'
}

bytes2kib() {
	set -- "$(cat)"
	test "$1" -gt 0 && echo $(($1 / 1024))
}


case $(uname -s)
in
	Darwin)
		sysctl -n hw.memsize | bytes2kib
		;;
	FreeBSD|NetBSD|OpenBSD)
		PATH="${PATH}:/usr/local/sbin:/usr/sbin:/sbin"
		sysctl -n hw.physmem | bytes2kib
		;;
	*)
		if test -r /proc/meminfo
		then
			awk -F ': +' '$1 == "MemTotal" { sub(/B$/, "iB", $2); print $2 }' /proc/meminfo \
			 | str2bytes \
			 | bytes2kib
		fi
		;;
esac
