#!/bin/sh -e
#
# 2020 Dennis Camera (dennis.camera@ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

in_list() { printf '%s\n' "$@" | { grep -qxF "$(read -r NDL; echo "$NDL")"; } }

os=$(cat "$__global/explorer/os")

state_is=$(cat "${__object}/explorer/state")
state_should=$(cat "${__object}/parameter/state")

case $os
in
	(openwrt)
		:
		;;
	(*)
		printf "Your operating system (%s) is currently not supported by this type (%s)\n" "$os" "${__type##*/}" >&2
		printf "Please contribute an implementation for it if you can.\n" >&2
		exit 1
		;;
esac

needs_changes=false
case $state_should
in
	(present)
		# NOTE: order is ignored so rearranged is also fine.
		in_list "${state_is}" 'present' 'rearranged' || needs_changes=true
		;;
	(absent)
		in_list "${state_is}" 'absent' || needs_changes=true
		;;
	(*)
		printf 'Invalid --state: %s\n' "${state_should}" >&2
		exit 1
		;;
esac

if $needs_changes
then
	# Make sure the changes are being commited
	require=$__object_name \
	__uci_commit "$(cat "${__object}/parameter/transaction")"
fi
